language: csharp
solution: Map.sln
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      - wsu-ucomm:ckdqKilnpWQpuiqMvZncaLQT
    on_success: change
    on_failure: always
    on_start: never
before_install:
  - sudo apt-get install nunit-console
 matrix:
  include:
    - env: TRAVIS_NODE_VERSION="stable"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
 
before_script:
  - npm install 
  - bower install
  - nuget restore Map.sln
script:
  - xbuild /p:Configuration=Release Map.sln
  - nunit-console Map.Tests/bin/Release/Map.Tests.dll
  - grunt
