language: csharp
solution: Map.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - npm install -g bower
  - nuget restore Map.sln
after_script:
  - nunit-console Map.Tests/bin/Release/Map.Tests.dll
