language: csharp
solution: Map.sln
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      - wsu-ucomm:ckdqKilnpWQpuiqMvZncaLQT
    on_success: change
    on_failure: always
    on_start: never
before_install:
  - sudo apt-get install nunit-console
before_script:
  - npm install -g bower
  - nuget restore Map.sln
script:
  - nunit-console Map.Tests/bin/Release/Map.Tests.dll